//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class productss
    {
        public int ppid { get; set; }
        public string pptitle { get; set; }
        public double ppprice { get; set; }
        public int ccid { get; set; }
    }
}
