//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace signup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Userid { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Password { get; set; }
        public bool Ismailverified { get; set; }
        public System.Guid Activationcode { get; set; }

        public string ConfirmPassword { get; set; }
    }
}
