//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelSecEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro
    {
        public int proid { get; set; }
        public string proname { get; set; }
        public double proprice { get; set; }
        public int catid { get; set; }
    }
}
