//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelThird
{
    using System;
    using System.Collections.Generic;
    
    public partial class prou
    {
        public int prouid { get; set; }
        public double prouprice { get; set; }
        public string proutitle { get; set; }
        public int catuid { get; set; }
    }
}
